In [ ]:
import pandas as pd

In [ ]:
dataset = pd.read_csv("/content/winequality-red.csv")

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [ ]:
dataset

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.4             0.700         0.00  ...       0.56      9.4        5
1               7.8             0.880         0.00  ...       0.68      9.8        5
2               7.8             0.760         0.04  ...       0.65      9.8        5
3              11.2             0.280         0.56  ...       0.58      9.8        6
4               7.4             0.700         0.00  ...       0.56      9.4        5
...             ...               ...          ...  ...        ...      ...      ...
1594            6.2             0.600         0.08  ...       0.58     10.5        5
1595            5.9             0.550         0.10  ...       0.76     11.2        6
1596            6.3             0.510         0.13  ...       0.75     11.0        6
1597            5.9             0.645         0.12  ...       0.71     10.2        5
1598            6.0             0.310         0.47  ...       0.66     11.0        6

[1599 rows x 12 columns]

#Preparing Data for clarification
    the quality of the wine is split into 'Good' and 'Bad' based on the rating it has been given
    

In [ ]:
quality = dataset["quality"].values
category = []
for num in quality:
    if num<=6:
        category.append("Bad")
    else :
        category.append("Good")

In [ ]:
category = pd.DataFrame(data=category, columns=["Quality_class"])

In [ ]:
dataset1 = pd.concat([dataset,category],axis=1)
dataset1.drop(columns="quality",axis=1,inplace=True)

In [ ]:
dataset1

fixed acidity  volatile acidity  ...  alcohol  Quality_class
0               7.4             0.700  ...      9.4            Bad
1               7.8             0.880  ...      9.8            Bad
2               7.8             0.760  ...      9.8            Bad
3              11.2             0.280  ...      9.8            Bad
4               7.4             0.700  ...      9.4            Bad
...             ...               ...  ...      ...            ...
1594            6.2             0.600  ...     10.5            Bad
1595            5.9             0.550  ...     11.2            Bad
1596            6.3             0.510  ...     11.0            Bad
1597            5.9             0.645  ...     10.2            Bad
1598            6.0             0.310  ...     11.0            Bad

[1599 rows x 12 columns]

In [ ]:
X= dataset1.iloc[:,:-1].values
y=dataset1.iloc[:,-1].values

In [ ]:
from sklearn.preprocessing import LabelEncoder
le =LabelEncoder()
y= le.fit_transform(y)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2,random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

#Importing and Applying Different Classification Algorithms

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [ ]:
l_cla = LogisticRegression()
k_cla = KNeighborsClassifier()
d_cla = DecisionTreeClassifier()
r_cla = RandomForestClassifier()
s_cla = SVC(kernel='linear')
ks_cla = SVC(kernel= 'rbf')

In [ ]:
l_cla.fit(X_train, y_train)
k_cla.fit(X_train, y_train)
d_cla.fit(X_train, y_train)
r_cla.fit(X_train, y_train)
s_cla.fit(X_train, y_train)
ks_cla.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [ ]:
l_pred = l_cla.predict(X_test)
k_pred = k_cla.predict(X_test)
d_pred = d_cla.predict(X_test)
r_pred = r_cla.predict(X_test)
s_pred = s_cla.predict(X_test)
ks_pred = ks_cla.predict(X_test)

#Confusion Matrices For each Algorithms

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
l_c = confusion_matrix(y_test, l_pred)
k_c = confusion_matrix(y_test, k_pred)
d_c = confusion_matrix(y_test, d_pred)
r_c = confusion_matrix(y_test, r_pred)
s_c = confusion_matrix(y_test, s_pred)
ks_c = confusion_matrix(y_test, ks_pred)

In [ ]:
l_c

array([[277,  13],
       [ 18,  12]])

In [ ]:
k_c

array([[276,  14],
       [ 13,  17]])

In [ ]:
d_c

array([[264,  26],
       [  9,  21]])

In [ ]:
r_c

array([[281,   9],
       [ 12,  18]])

In [ ]:
s_c

array([[290,   0],
       [ 30,   0]])

In [ ]:
ks_c

array([[285,   5],
       [ 21,   9]])

#Accuracy Score Of the algorithms

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
l_a = accuracy_score(y_test, l_pred)
k_a = accuracy_score(y_test, k_pred)
d_a = accuracy_score(y_test, d_pred)
r_a = accuracy_score(y_test, r_pred)
s_a = accuracy_score(y_test, s_pred)
ks_a = accuracy_score(y_test, ks_pred)

In [ ]:
print('Logistic Regression: ' + str(l_a) + '\nKNN : ' + str(k_a) + '\nDecision Tree: ' + str(d_a) + '\nRandom Forest: ' + str(r_a) + '\nLinear SVC: ' + str(s_a) + '\nKernel SVC: ' + str(l_a))

Logistic Regression: 0.903125
KNN : 0.915625
Decision Tree: 0.890625
Random Forest: 0.934375
Linear SVC: 0.90625
Kernel SVC: 0.903125


random forest has given the best result


#Preparing Data for Regression

In [ ]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [ ]:
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2)

In [ ]:
from sklearn.preprocessing import StandardScaler
t_train = y_train.reshape(len(y_train),1)
t_test = y_test.reshape(len(y_test),1)
X_sc = StandardScaler()
y_sc = StandardScaler()

In [ ]:
X_std_train = X_sc.fit_transform(X_train)
y_std_train = y_sc.fit_transform(t_train)

In [ ]:
X_std_test = X_sc.transform(X_test)
y_std_test = y_sc.transform(t_test)

#Importing and Applying Different Regression Algorithms

In [ ]:
from sklearn.linear_model import LinearRegression 
from sklearn.preprocessing import PolynomialFeatures
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR

In [ ]:
m_reg=LinearRegression()
p_reg=LinearRegression()
d_reg=DecisionTreeRegressor()
r_reg=RandomForestRegressor()
s_reg=SVR()

In [ ]:
X_poly = PolynomialFeatures(degree=2)
X_poly = X_poly.fit_transform(X_train)

In [ ]:
m_reg.fit(X_train,y_train)
p_reg.fit(X_poly,y_train)
r_reg.fit(X_train,y_train)
d_reg.fit(X_train,y_train)
s_reg.fit(X_std_train,y_std_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [ ]:
temp = PolynomialFeatures(degree =2)
temp = temp.fit_transform(X_test)


In [ ]:
m_pred=m_reg.predict(X_test)
p_pred=p_reg.predict(temp)
r_pred=r_reg.predict(X_test)
d_pred=d_reg.predict(X_test)
s_pred=s_reg.predict(X_std_test)

#Finding the R^2 score

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
m= r2_score(y_test,m_pred)
p= r2_score(y_test,p_pred)
r= r2_score(y_test,r_pred)
d= r2_score(y_test,d_pred)
s= r2_score(y_std_test,s_pred)


In [ ]:
print('Linear Regression: ' + str(m) + '\nPolynomial Regression. : ' + str(p) + '\nDecision Tree: ' + str(d) + '\nRandom Forest: ' + str(r) + '\nSupport Vector Regression SVC: ' + str(s) )

Linear Regression: 0.35329961492187667
Polynomial Regression. : 0.37400355110975525
Decision Tree: 0.07080409976299229
Random Forest: 0.49923422956789254
Support Vector Regression SVC: 0.4118753172042309


The above result shows R^2 score to be the highest for Random Forest Regression Algorithm

#Conclusion

Hence in conclusion, for both Classification and Regression, Random Forest Algorithm is giving the best result